dist: trusty
addons:
  chrome: stable

language: ruby
rvm:
  - 2.6.6

script:
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
 - bundle exec rails test
 - bundle exec rails test:system
