dist: trusty

language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1

script:
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
 - bundle exec rails test
 - bundle exec rails test:system
